### PR TITLE
Fixed deadlock in MakeShardFn on static var assignment under free-threading

### LINKED ISSUE #28385: Deadlock in MakeShardFn function under free-threading
### Description

When running `string_array_test_cpu` under python 3.13-ft and TSAN, I see the following deadlock:

```
Thread 142 (Thread 0x7ffecde006c0 (LWP 86763) "string_array_te"):
#0  0x000055555560bd0e in __sanitizer::FutexWait(__sanitizer::atomic_uint32_t*, unsigned int) ()
#1  0x0000555555631ce8 in __cxa_guard_acquire ()
#2  0x00007ffeee391812 in xla::(anonymous namespace)::MakeShardFn (arg=arg@entry=..., client=client@entry=0x72440000b180, to_device=0x7234000075d0, to_memory_kind=..., options=...) at jaxlib/py_values.cc:595

```

and
```
Thread 141 (Thread 0x7ffecd4006c0 (LWP 86764) "string_array_te"):
#0  0x00007ffff7d14d71 in __futex_abstimed_wait_common64 (private=<optimized out>, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x7ffecd3fcd50) at ./nptl/futex-internal.c:57
#1  __futex_abstimed_wait_common (cancel=true, private=<optimized out>, abstime=0x0, clockid=0, expected=0, futex_word=0x7ffecd3fcd50) at ./nptl/futex-internal.c:87
#2  __GI___futex_abstimed_wait_cancelable64 (futex_word=futex_word@entry=0x7ffecd3fcd50, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=<optimized out>) at ./nptl/futex-internal.c:139
#3  0x00007ffff7d20f1f in do_futex_wait (sem=sem@entry=0x7ffecd3fcd50, abstime=0x0, clockid=0) at ./nptl/sem_waitcommon.c:111
#4  0x00007ffff7d20fb8 in __new_sem_wait_slow64 (sem=0x7ffecd3fcd50, abstime=0x0, clockid=0) at ./nptl/sem_waitcommon.c:183
#5  0x00005555556632fa in __interceptor_sem_wait ()
#6  0x00005555559decfb in _PySemaphore_PlatformWait (sema=0x7ffecd3fcd50, timeout=-1) at Python/parking_lot.c:149
#7  _PySemaphore_Wait (sema=sema@entry=0x7ffecd3fcd50, timeout=timeout@entry=-1, detach=detach@entry=0) at Python/parking_lot.c:220
#8  0x00005555559defcd in _PyParkingLot_Park (addr=addr@entry=0x72a400014028, expected=expected@entry=0x7ffecd3fcdcc, size=size@entry=4, timeout_ns=timeout_ns@entry=-1, park_arg=park_arg@entry=0x0, detach=detach@entry=0) at Python/parking_lot.c:323
#9  0x00005555559f0b1b in tstate_wait_attach (tstate=<optimized out>) at Python/pystate.c:2066
#10 _PyThreadState_Attach (tstate=tstate@entry=0x72a400014000) at Python/pystate.c:2096
#11 0x00005555559a7b7b in PyEval_AcquireThread (tstate=tstate@entry=0x72a400014000) at Python/ceval_gil.c:602
#12 0x00005555559ded83 in _PySemaphore_Wait (sema=sema@entry=0x7ffecd3fceb0, timeout=timeout@entry=-1, detach=detach@entry=1) at Python/parking_lot.c:222
#13 0x00005555559defcd in _PyParkingLot_Park (addr=addr@entry=0x555555d75f78 <_PyRuntime+308856>, expected=expected@entry=0x7ffecd3fcf2f, size=size@entry=1, timeout_ns=timeout_ns@entry=-1, park_arg=park_arg@entry=0x7ffecd3fcf48, detach=detach@entry=1) at Python/parking_lot.c:323
#14 0x00005555559d42ef in _PyMutex_LockTimed (m=m@entry=0x555555d75f78 <_PyRuntime+308856>, timeout=timeout@entry=-1, flags=flags@entry=_PY_LOCK_DETACH) at Python/lock.c:108
#15 0x00005555559d5002 in PyMutex_Lock (m=m@entry=0x555555d75f78 <_PyRuntime+308856>) at Python/lock.c:584
#16 0x0000555555980e49 in _PyMutex_Lock (m=0x555555d75f78 <_PyRuntime+308856>) at ./Include/cpython/lock.h:49
#17 _PyCriticalSection_BeginSlow (c=c@entry=0x7ffecd3fd010, m=m@entry=0x555555d75f78 <_PyRuntime+308856>) at Python/critical_section.c:20
#18 0x000055555583b291 in _PyCriticalSection_BeginMutex (c=0x7ffecd3fd010, m=0x555555d75f78 <_PyRuntime+308856>) at ./Include/internal/pycore_critical_section.h:119
#19 _PyType_LookupRef (type=type@entry=0x555555d06520 <PyModule_Type>, name=name@entry=0x7fffbe0d0c40) at Objects/typeobject.c:5288
#20 0x00005555557ea81a in _PyObject_GenericGetAttrWithDict (obj=obj@entry=0x7fffb5e75a00, name=name@entry=0x7fffbe0d0c40, dict=dict@entry=0x0, suppress=suppress@entry=1) at Objects/object.c:1659
#21 0x00005555557e24ed in _Py_module_getattro_impl (m=m@entry=0x7fffb5e75a00, name=name@entry=0x7fffbe0d0c40, suppress=suppress@entry=1) at Objects/moduleobject.c:927
#22 0x00005555557e7c11 in PyObject_GetOptionalAttr (v=v@entry=0x7fffb5e75a00, name=0x7fffbe0d0c40, result=result@entry=0x7ffecd3fd1d8) at Objects/object.c:1315
#23 0x00005555557e93be in PyObject_GetOptionalAttrString (obj=obj@entry=0x7fffb5e75a00, name=name@entry=0x7ffef408e9be "int2", result=result@entry=0x7ffecd3fd1d8) at Objects/object.c:1359
#24 0x00005555557e90fd in PyObject_HasAttrStringWithError (obj=obj@entry=0x7fffb5e75a00, name=name@entry=0x7ffef408e9be "int2") at Objects/object.c:1140
#25 0x00005555557e95ff in PyObject_HasAttrString (obj=0x7fffb5e75a00, name=0x7ffef408e9be "int2") at Objects/object.c:1149
#26 0x00007ffeefc994de in nanobind::hasattr (h=..., key=0x7ffef408e9be "int2") at external/nanobind/include/nanobind/nb_types.h:276
#27 xla::GetNumpyScalarTypes()::$_0::operator()() const (this=<optimized out>) at external/xla/xla/python/types.cc:406
#28 0x00007ffeefc99282 in xla::GetNumpyScalarTypes () at external/xla/xla/python/types.cc:401
#29 0x00007ffeee3974d5 in xla::(anonymous namespace)::MakeShardFn(nanobind::handle, xla::ifrt::Client*, xla::ifrt::Device*, xla::ifrt::MemoryKind, xla::DevicePutOptions const&)::$_0::operator()() const (this=<optimized out>) at jaxlib/py_values.cc:598
#30 0x00007ffeee39181f in xla::(anonymous namespace)::MakeShardFn (arg=arg@entry=..., client=client@entry=0x72440000b180, to_device=0x7234000075d0, to_memory_kind=..., options=...) at jaxlib/py_values.cc:596
```

Full report: https://gist.github.com/vfdev-5/cb8009c349ca99765d4a8fe98f81d150

Report makes sense as underlying function has comment "Requires GIL":

https://github.com/jax-ml/jax/blob/a49adaca4c402eb77c6336d4f2fb118dd5ff4854/jaxlib/py_values.cc#L590-L596

Test command:
```bash
bazel test     --test_env=JAX_NUM_GENERATED_CASES=10     --test_env=JAX_ENABLE_X64=true     --test_env=JAX_SKIP_SLOW_TESTS=true     --test_env=PYTHON_GIL=0     --test_env=TSAN_OPTIONS=suppressions=$PWD/.github/workflows/tsan-suppressions_3.13.txt     --test_env=JAX_TEST_NUM_THREADS=30     --test_ou
tput=errors         --local_test_jobs=10     --test_timeout=3600        --nocache_test_results --runs_per_test=100       //tests:string_array_test_cpu &> bazel_string_a
rray_test_cpu.log
```

### System info (python version, jaxlib version, accelerator, etc.)

TSAN 3.13-ft cpython
Linux

### PR DESCRIPTION
**Pull request by vfdev-5**
Description:
- Fixed deadlock in MakeShardFn on static var assignment under free-threading using nb::ft_mutex

Fixes #28385

### CODE REVIEW

File: jaxlib/py_values.cc [hunk 1]
```diff
@@ -592,8 +592,19 @@ absl::StatusOr<ShardFn> MakeShardFn(nb::handle arg, ifrt::Client* client,
...
-                                   DevicePutHandler>* const handlers = [] {
+  const absl::flat_hash_map<PyObject*,
+                            DevicePutHandler>* const handlers = [] {
+
+    // static variable assignment can deadlock under free-threading
+    // use nb mutex and lock to prevent it:
+    static nb::ft_mutex mu;
+    static absl::flat_hash_map<PyObject*, DevicePutHandler>* output = nullptr;
+    {
+      nb::ft_lock_guard lock(mu);
```
Comment (hawkinsp) [inline jaxlib/py_values.cc:603]: You need to use an absl::Mutex here because this lock should apply even in a GIL-enabled build.

File: jaxlib/py_values.cc [hunk 2]
```diff
@@ -592,8 +592,19 @@ absl::StatusOr<ShardFn> MakeShardFn(nb::handle arg, ifrt::Client* client,
...
                                     ifrt::MemoryKind to_memory_kind,
                                     const DevicePutOptions& options) {
-  static const absl::flat_hash_map<PyObject*,
-                                   DevicePutHandler>* const handlers = [] {
+  const absl::flat_hash_map<PyObject*,
+                            DevicePutHandler>* const handlers = [] {
+
+    // static variable assignment can deadlock under free-threading
+    // use nb mutex and lock to prevent it:
+    static nb::ft_mutex mu;
```
Comment (hawkinsp) [inline jaxlib/py_values.cc:600]: We've now had to write this initialization pattern twice, the other time in NamedSharding::NamedSharding. I would be tempted to add a helper class for it and use it in both places?

**Review by hawkinsp — CHANGES_REQUESTED** [review]

**Review by hawkinsp — APPROVED** [review]

**Review by hawkinsp — CHANGES_REQUESTED** [review]
You need to update the BUILD file entries to depend directly on the XLA library you added.

**Review by hawkinsp — APPROVED** [review]
